Port `ExternalTester` from the JS codebase
apollographql/federation-next pull request #231
Opened 2024-03-14 15:02 UTC by sachindshinde

This PR:
- Adds subgraph metadata (known as `FederationMetadata` in the JS codebase) to the schema representation, but doesn't port all the logic there.
- Ports external metadata (known as `ExternalTester` in the JS codebase).

2024-03-26 15:18 UTC, goto-bus-stop requested changes
Implementation looks correct, just some Rusty comments!

2024-04-04 15:35 UTC, goto-bus-stop commented on src/schema/mod.rs
> +    subgraph_metadata: Option<SubgraphMetadata>,
Oh, this is also an issue, `SubgraphMetadata` is not cheap to clone but is part of `ValidFederationSchema` which (in theory) is.

I think we need to tweak the order of initialisation to fix this and maybe let SubgraphMetadata work on not-necessarily-valid federation schemas.

2024-04-04 15:55 UTC, goto-bus-stop commented
I hope it's okay that I addressed my own feedback, that's how I interpreted it in the meeting yesterday, and I was looking for something fun to do!

2024-04-04 16:08 UTC, goto-bus-stop commented
`FederationSchema` is used for supergraphs and subgraphs, maybe this should be included in a wrapper type that's only for subgraphs?

2024-04-09 07:52 UTC, goto-bus-stop commented
I moved `SubgraphMetadata` to be part of `FederationSchema` instead of `ValidFederationSchema`, but it's only populated in the `ValidFederationSchema` constructor and it can only be accessed through a `ValidFederationSchema`.

I think we should have separate types for subgraph and supergraph schemas, since the code always knows which one it is operating on, and they require different data and different handling.

2024-04-16 12:00 UTC, lrlna approved these changes

2024-04-16 12:00 UTC, merged