FED-189: port extractDeferFromOperation
apollographql/federation-next pull request #284
Opened 2024-04-26 18:32 UTC by duckki

Implemented `extract_defer_from_operation` function.

Even though most of its functionality is not used until `@defer` is actually implemented, it's called from `compute_nodes_for_op_path_element` and we needed some implementation anyways.

2024-04-27 01:03 UTC, duckki commented
About the `FetchDependencyGraphPath` => `FetchDependencyGraphNodePath` change, see [my Slack discussion with Sachin](https://apollograph.slack.com/archives/C05263RUETS/p1714178621288419).

2024-04-29 17:18 UTC, TylerBloom requested changes
Looks good overall, just a few places to be cleaned up, I think. :)

2024-04-29 17:18 UTC, TylerBloom commented on src/query_plan/fetch_dependency_graph.rs
> +    pub(crate) response_path: Vec<FetchDataPathElement>,
Let's limit visibility for fields that don't need to be made public.
```suggestion
    path_in_node: Arc<OpPath>,
    response_path: Vec<FetchDataPathElement>,
```

2024-04-29 17:18 UTC, TylerBloom commented on src/query_plan/fetch_dependency_graph.rs
> +    let Some(ref updated_defer_ref) = defer_args.label else {
Use the existing `label` method:
```suggestion
    let Some(updated_defer_ref) = defer_args.label() else {
```

2024-04-29 17:18 UTC, TylerBloom commented on src/query_plan/fetch_dependency_graph.rs
> +        ));
Also, this is more stylistic, but using `Option::ok_or_else` + a try operator (i.e. `?`) is often an easier-to-read way of short-circuiting a function that returns a `Result` when you have an `Option`. Not a necessary change, as both ways will compile to basically the same thing, but I figured I would mention it.

2024-04-29 17:54 UTC, duckki commented
@TylerBloom Thanks for the review! I just accepted your suggestions and pushed it.

2024-04-29 18:30 UTC, merged